### ISSUE TITLE
OpenVPN can be detected

### ISSUE THREAD

**Issue by dmitry** [jpetazzo/dockvpn#24]
Because of using non-standard MTU openVPN can be detected: http://witch.valdikss.org.ru/

**Comment by jpetazzo** [comment]
I think this is not related to `dockvpn`, so I will close this issue :-)

If you think otherwise, or have a suggestion of action, let me know, I'll be happy to re-open.

Thank you!

**Comment by dmitry** [comment]
@jpetazzo have you tried to access the page above through the dockvpn? In my case it shows that I've requested a page though OpenVPN. 

Some more information how to prevent from that detection: https://medium.com/@ValdikSS/detecting-vpn-and-its-configuration-and-proxy-users-on-the-server-side-1bcc59742413

**Comment by jpetazzo** [comment]
If someone wants to provide a pull request (or even a paragraph to add to the README), that's cool; but otherwise I think it's outside of the scope of dockvpn :-)

Thank you for this resource, though; it's very instructive!
