### ISSUE TITLE
OS X Works

### ISSUE THREAD

**Issue by mattwilliamson** [jpetazzo/dockvpn#25]
Thanks for your easy to use VPN server. I just want to confirm that it works well with Viscosity on Mac. I did have to import, then export then re-import again to get it to work due to `dh.key` missing, but it could easily be a bug with the client.

**Comment by sbusso** [comment]
This is definitely helpful, Thank you.

**Comment by jpetazzo** [comment]
Thanks for reporting this; I added this info to the README.
