### ISSUE TITLE
Exposing OpenVpn TUN @IP for Swarm cluster

### ISSUE THREAD

**Issue by besn0847** [jpetazzo/dockvpn#26]
Hi Jérôme,

Great stuff ! Thanks ! You saved me lot of time :) 
Here is a lighter version (~15m) https://github.com/besn0847/alpinevpn (warning : i removed the 443/tcp part - will re-include in the future).

Otherwise, i have a question on how to get the IP address of the TUN device in the container.

I'm trying to build an ARM-based (rasp pi 2) Swarm cluster over the internet (goal is to make my life easier to manage those things spread across my family). Swarm assumes "static IP" address when declared in Consul, etcd... So a VPN seems to be the easiest way so far.

But, if i start another container to advertise the VPN IP to Consul, i need to be able to gather the TUN device IP of the VPN container. Is there a way to do so ? Linkage ?

I could start an advertiser in the openvpn container but i prefer to have one process per container.

Thanks in advance if you can help.
Franck

**Comment by pierreozoux** [comment]
Arf, this is something I'm looking for also :)
https://github.com/docker/swarm/issues/1458

(Yes, I know, we, users, are never satisfied :) this is maybe the beauty and the worse about humanity :) )

**Comment by besn0847** [comment]
Sorted my issue by building an all-inclusive Swarm manager container. OK nasty but i needed quick & dirty so far :)
Source : https://github.com/besn0847/armswarm

**Comment by sumkincpp** [comment]
With the new swarm mode, grid vpn(i.e. "swarm mode openvpn") solution may become ubiquitous app!

**Comment by jpetazzo** [comment]
Cool! I added a link to alpinevpn in the README, since this could be useful to other folks. Tanks!
