### ISSUE TITLE
How to keep the same configuration file after a reboot

### ISSUE THREAD

**Issue by maxlath** [jpetazzo/dockvpn#32]
I'm new to the docker world so I might miss something obvious, but I can't find a way to restore the VPN container to use the same configuration after a server reboot: do you update your configuration every times or is there a trick to persist and restore the generated config?
Thanks for this awesome project!

**Comment by jpetazzo** [comment]
It generates a new configuration each time it's started. However, the configuration is kept in a volume, so if you reuse the same volume across reboots it should stick!

(I can't remember if I had tested this when I wrote this a while ago, sorry! But it should be fairly straightforward :))

**Comment by maxlath** [comment]
nice, thanks!
