### ISSUE TITLE
Random ip-address

### ISSUE THREAD

**Issue by GlennTvein** [jpetazzo/dockvpn#37]
Hi there! Thanks for great stuff!
Is there a way to make ip-addresses static for devices inside the VPN? And/or how to get list of ip-addresses of connected devices?

The goal is to set determined ip-address for each device inside vpn network. Now all ip-addresses are dynamic so i cant connect to my devices (orangepis) after reconnect/reboot because ip-address alter everytime.

**Comment by jpetazzo** [comment]
Hi!

This would be an OpenVPN question; I would suggest to check OpenVPN documentation / mailing lists / etc., then you can add whatever configuration instructions to the configuration in the Docker image.

Thank you!
