### ISSUE TITLE
Docker Hub images outdated

### ISSUE THREAD

**Issue by coolOpenSourceDev** [jpetazzo/dockvpn#43]
For some reasons Docker Hub images for this repo were outdated.

https://hub.docker.com/r/jpetazzo/dockvpn/dockerfile
`By [jpetazzo](https://hub.docker.com/u/jpetazzo) • Updated 3 years ago`

Could you please update Docker Hub image?

**Comment by jpetazzo** [comment]
Hi!

These images were using "automated builds", which are now deprecated (I think?)

I'm currently away for travel. When I get back home I'll set up automated builds with GitHub Actions :)

**Comment by jpetazzo** [comment]
I've set up GHA to automatically build images for both Intel and ARM 64 bits. We have up-to-date images now :)
