### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by aviau** [jpetazzo/dockvpn#7]
Hello!

I am still new to docker. I just ran your image and I got "exec format error".
I also get: "finalize namespace drop capabilities operation not permitted"

Is this image still working?

**Comment by aerodame** [comment]
I'm getting this same error also...

Docker_1.7.1/docker# sudo make build
mkdir bundles
docker build -t "docker-dev:HEAD" .
Sending build context to Docker daemon 75.81 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
Pulling repository ubuntu
91e54dfb1179: Download complete 
d3a1f33e8a5a: Download complete 
c22013c84729: Download complete 
d74508fb6632: Download complete 
 ---> 91e54dfb1179
Step 1 : MAINTAINER Tianon Gravi <admwiggin@gmail.com> (@tianon)
 ---> Running in 8e3f314f7df6
 ---> f1413c8ee247
Removing intermediate container 8e3f314f7df6
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in de8695f49355
2015/08/25 16:51:45 exec format error
2015/08/25 18:51:46 The command [/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61] returned a non-zero code: 1
make: *** [build] Error 1

# uname -a
Linux cubox-i 3.14.14+ #1 SMP Tue Aug 25 02:48:24 CEST 2015 armv7l armv7l armv7l GNU/Linux

**Comment by jpetazzo** [comment]
@aerodame : that's because you're running on Arm. That's not supported officially (at least, not yet!)

Sorry!
